# Generated by Django 4.0.3 on 2022-04-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
